CREATE TABLE CLIENTES(ID_CLIENTE INTEGER AUTO_INCREMENT PRIMARY KEY, 
						NOME VARCHAR(200) NOT NULL,
						CPF VARCHAR(11) NOT NULL,
						DATA_NASCIMENTO DATETIME);				
					
CREATE TABLE FILMES(ID_FILME INTEGER AUTO_INCREMENT PRIMARY KEY, 
						TITULO VARCHAR(100) NOT NULL,
						CLASSIFICACAO_INDICATIVA INTEGER ,
                        LANCAMENTO TINYINT
                       );

CREATE TABLE LOCACOES(ID_LOCACAO INTEGER AUTO_INCREMENT PRIMARY KEY, 
						ID_CLIENTE INTEGER,
						ID_FILME INTEGER,
						DATA_CRIACAO  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                        DATA_LOCACAO DATETIME,
						DATA_DEVOLUCAO DATETIME,
						FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
                        FOREIGN KEY(ID_FILME) REFERENCES FILMES(ID_FILME)                     
					);
